site_name: IND!ENATION

theme:
  name: material
  features:
    - navigation.tabs
  font:
    code: Open Sans
  palette:
    primary : teal



markdown_extensions:
  - attr_list
  - md_in_html

nav:
  - IND!ENATION : index.md
  - Ratings:
    - 2023:
      - Oct: Ratings/2023/Oct.md
  - Reviews:
    - 2023:
      - Oct:
        - CMAT - Crazymad, for Me: Reviews/2023/10/CMAT.md
        - Samph - Lahai: Reviews/2023/10/Sampha.md
        - Jamilia Woods - Water Made Us: Reviews/2023/10/Woods.md
        - boygenius - the rest - EP : Reviews/2023/10/boygenius.md
  - Album Lists:
    - Consolidated Lists:
      - 2023 Year-End: ALists/Consolidated/111.md
    - Personal List:
      - 2023:
        - 某妈: ALists/Personal/2023/hello.md
  - Single Lists:
    - Consolidated Lists:
      - 2022 Year-End: SLists/Consolidated/2022E.md
      - 2021 Year-End: SLists/Consolidated/2021E.md
      - 2020 Year-End: SLists/Consolidated/2020E.md
    - Personal List:
      - 2023:
        - 某妈: SLists/Personal/2023/hello.md
  - Events:
    - 2023:
      - IND!ENATION 42: Events/2023/INDIENATION42/42.md